Repository NethermindEth/Paprika, pull requests merged in 2023-06, with the labels that each got.

#94 Hashing map
  src/Paprika.Runner/Program.cs
  src/Paprika.Tests/Data/KeyTests.cs
  src/Paprika.Tests/HashingMapTests.cs
  src/Paprika.Tests/Store/DataPageTests.cs
  src/Paprika.Tests/Store/DbTests.cs
  src/Paprika.Tests/TestExtensions.cs
  src/Paprika.Tests/Values.cs
  src/Paprika/Data/HashingMap.cs
  src/Paprika/Data/Key.cs
  src/Paprika/Data/NibbleBasedMap.cs
  src/Paprika/Data/NibblePath.cs
  src/Paprika/Store/DataPage.cs
  src/Paprika/Store/PagedDb.cs
  src/Paprika/Store/SetContext.cs
Labels: 🐌 performance

#95 Flushing changed
  src/Paprika.Runner/Program.cs
  src/Paprika.Tests/TestExtensions.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Store/IPageManager.cs
  src/Paprika/Store/PageManagers/MemoryMappedPageManager.cs
  src/Paprika/Store/PageManagers/NativeMemoryPageManager.cs
  src/Paprika/Store/PageManagers/PointerPageManager.cs
  src/Paprika/Store/PagedDb.cs
Labels: 🐌 performance

#96 Merkle foundations with pre-commit hook
  src/Paprika.Runner/Program.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Chain/IPreCommitBehavior.cs
Labels: ethereum

#97 Fix for the write error
  src/Paprika.Runner/Program.cs
  src/Paprika.Tests/Store/DataPageTests.cs
  src/Paprika.Tests/Store/DbAddressTests.cs
  src/Paprika.Tests/TestExtensions.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Crypto/Keccak.cs
  src/Paprika/Data/Key.cs
  src/Paprika/Data/NibbleBasedMap.cs
  src/Paprika/Store/DataPage.cs
  src/Paprika/Store/DbAddress.cs
  src/Paprika/Store/PageManagers/MemoryMappedPageManager.cs
  src/Paprika/Store/PageManagers/PointerPageManager.cs
  src/Paprika/Store/PagedDb.cs
Labels: bug

#98 (De)serialization of Merkle Nodes
  src/Paprika.Tests/Merkle/NodeTests.cs
  src/Paprika/Crypto/Keccak.cs
  src/Paprika/Merkle/Node.cs
Labels: ethereum

#108 Dangling readonly batch fix
  src/Paprika.Runner/Program.cs
  src/Paprika/Chain/Blockchain.cs
Labels: bug

#109 HasingMap entry size fixup
  src/Paprika.Tests/HashingMapTests.cs
  src/Paprika/Data/HashingMap.cs
Labels: bug
