Repository NethermindEth/Paprika, pull requests merged in 2024-03, with the labels that each got.

#271 Delayed metrics introduced
  src/Paprika.Runner/Measurement.cs
  src/Paprika.Tests/Chain/BlockchainTests.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Utils/DelayedMetrics.cs
  src/Paprika/Utils/Metrics.cs
Labels: 🐌 performance

#273 Merkle scatter gather simplified
  src/Paprika.Tests/Chain/BlockchainTests.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
Labels: 🐌 performance, 🌴Merkle

#267 Dense slotted array
  src/Paprika.Benchmarks/Paprika.Benchmarks.csproj
  src/Paprika.Benchmarks/SlottedArrayBenchmarks.cs
  src/Paprika.Tests/Data/NibblePathTests.cs
  src/Paprika.Tests/Data/SlottedArrayTests.cs
  src/Paprika/Data/NibblePath.cs
  src/Paprika/Data/SlottedArray.cs
Labels: 💾 disk size, 💥Breaking

#264 Leaf + overflow
  src/Paprika.Importer/Paprika.Importer.csproj
  src/Paprika.Runner.Pareto/Paprika.Runner.Pareto.csproj
  src/Paprika.Runner/Paprika.Runner.csproj
  src/Paprika.Runner/StatisticsForPagedDb.cs
  src/Paprika.Tests/Chain/BlockchainTests.cs
  src/Paprika.Tests/Data/BitVector512Tests.cs
  src/Paprika.Tests/Data/UshortSlottedArrayTests.cs
  src/Paprika.Tests/Merkle/AdditionalTests.cs
  src/Paprika.Tests/Paprika.Tests.csproj
  src/Paprika.Tests/PrinterTests.cs
  src/Paprika.Tests/Store/BasePageTests.cs
  src/Paprika.Tests/Store/DataPageTests.cs
  src/Paprika.Tests/Store/DbTests.cs
  src/Paprika.Tests/Store/PageStructurePrintingTests.cs
  src/Paprika.Tests/Store/TreeView.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Data/BitVector.cs
  src/Paprika/Data/SlottedArray.cs
  src/Paprika/Data/UShortSlottedArray.cs
  src/Paprika/Merkle/CommitExtensions.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
  src/Paprika/Store/BatchContextBase.cs
  src/Paprika/Store/DataPage.cs
  src/Paprika/Store/FanOutList.cs
  src/Paprika/Store/FanOutPage.cs
  src/Paprika/Store/IBatchContext.cs
  src/Paprika/Store/IPageVisitor.cs
  src/Paprika/Store/IReporter.cs
  src/Paprika/Store/LeafOverflowPage.cs
  src/Paprika/Store/LeafPage.cs
  src/Paprika/Store/Page.cs
  src/Paprika/Store/PageManagers/PointerPageManager.cs
  src/Paprika/Store/PageType.cs
  src/Paprika/Store/PagedDb.cs
  src/Paprika/Store/RootPage.cs
  src/Paprika/Store/StorageFanOutPage.cs
  src/Paprika/Utils/Printer.cs
  src/Paprika/Utils/ReadOnlySpanOwner.cs
Labels: 💣 experimental, 🐌 performance, 💾 disk size, 💥Breaking

#277 Slotted array empty value
  src/Paprika.Tests/Data/SlottedArrayTests.cs
  src/Paprika/Data/SlottedArray.cs
Labels: bug

#276 Faster slotted array
  src/Paprika.Benchmarks/SlottedArrayBenchmarks.cs
  src/Paprika/Data/NibblePath.cs
  src/Paprika/Data/SlottedArray.cs
Labels: 🐌 performance

#281 Merkleization now uses native buffer pooling
  src/Paprika.Tests/Merkle/AdditionalTests.cs
  src/Paprika.Tests/Merkle/PageOwnerTests.cs
  src/Paprika.Tests/Merkle/RootHashFuzzyTests.cs
  src/Paprika.Tests/Merkle/RootHashTests.cs
  src/Paprika/Chain/BufferPool.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
  src/Paprika/Merkle/PageOwner.cs
Labels: 🐌 performance, 🌴Merkle

#283 Cache metrics usage fix
  src/Paprika/Chain/Blockchain.cs
Labels: bug

#284 Parallelism optional
  src/Paprika.Tests/Merkle/RootHashFuzzyTests.cs
  src/Paprika.Tests/Merkle/RootHashTests.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
Labels: 🌴Merkle

#287 Optimize structures
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Data/BitVector.cs
  src/Paprika/Data/NibblePath.cs
  src/Paprika/Data/SlottedArray.cs
  src/Paprika/Data/UShortSlottedArray.cs
  src/Paprika/Merkle/CommitExtensions.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
  src/Paprika/Merkle/Node.cs
  src/Paprika/RLP/RlpStream.cs
  src/Paprika/Store/AbandonedList.cs
  src/Paprika/Store/AbandonedPage.cs
  src/Paprika/Store/DbAddress.cs
  src/Paprika/Store/FanOutPage.cs
  src/Paprika/Store/IBatchContext.cs
  src/Paprika/Store/LeafOverflowPage.cs
  src/Paprika/Store/Page.cs
  src/Paprika/Store/PageManagers/PointerPageManager.cs
  src/Paprika/Store/PagedDb.cs
  src/Paprika/Store/RootPage.cs
  src/Paprika/Utils/Xor8.cs
Labels: 🐌 performance

#289 Optimize DataPage lookup
  src/Paprika.Tests/Store/DataPageTests.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Data/SlottedArray.cs
  src/Paprika/Store/DataPage.cs
  src/Paprika/Store/FanOutList.cs
  src/Paprika/Store/FanOutPage.cs
  src/Paprika/Store/LeafPage.cs
  src/Paprika/Store/Page.cs
  src/Paprika/Store/RootPage.cs
  src/Paprika/Store/StorageFanOutPage.cs
Labels: 🐌 performance

#291 Pipeline memory reads in Xor8.MayContain
  src/Paprika/Utils/Xor8.cs
Labels: 🐌 performance

#293 Shorter leafs
  src/Paprika.Tests/Merkle/NodeTests.cs
  src/Paprika/Data/NibblePath.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
  src/Paprika/Merkle/Node.cs
Labels: 💾 disk size, 🌴Merkle, 💥Breaking

#286 Merkle branch rlp memoization
  src/Paprika.Runner.Pareto/Program.cs
  src/Paprika.Runner/Program.cs
  src/Paprika.Runner/SingleAsyncGate.cs
  src/Paprika.Runner/StatisticsForPagedDb.cs
  src/Paprika.Tests/Chain/BlockchainTests.cs
  src/Paprika.Tests/Merkle/AdditionalTests.cs
  src/Paprika.Tests/Merkle/Commit.cs
  src/Paprika.Tests/Merkle/DirtyTests.cs
  src/Paprika.Tests/Merkle/NodeTests.cs
  src/Paprika.Tests/Merkle/RlpMemoTests.cs
  src/Paprika.Tests/Merkle/RootHashFuzzyTests.cs
  src/Paprika.Tests/Merkle/RootHashTests.cs
  src/Paprika.Tests/Store/PagedDbTests.cs
  src/Paprika.Tests/Utils/MetricsTests.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Chain/IPreCommitBehavior.cs
  src/Paprika/Data/SlottedArray.cs
  src/Paprika/Merkle/CommitExtensions.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
  src/Paprika/Merkle/Node.cs
  src/Paprika/Merkle/RlpMemo.cs
  src/Paprika/RLP/KeccakOrRlp.cs
  src/Paprika/Store/DataPage.cs
  src/Paprika/Store/FanOutList.cs
  src/Paprika/Store/FanOutPage.cs
  src/Paprika/Store/IReporter.cs
  src/Paprika/Store/LeafOverflowPage.cs
  src/Paprika/Store/LeafPage.cs
  src/Paprika/Store/Page.cs
  src/Paprika/Store/PagedDb.cs
  src/Paprika/Store/RootPage.cs
  src/Paprika/Store/StorageFanOutPage.cs
Labels: 🐌 performance, 🌴Merkle, 💥Breaking
