Repository NethermindEth/Paprika, pull requests merged in 2024-02, with the labels that each got.

#225 FanOut page fixup
  src/Paprika.Importer/PaprikaCopyingVisitor.cs
  src/Paprika.Importer/PathContext.cs
  src/Paprika.Importer/Program.cs
  src/Paprika.Runner.Pareto/Program.cs
  src/Paprika.Tests/Store/PagedDbTests.cs
  src/Paprika/Store/FanOutPage.cs
  src/Paprika/Store/PagedDb.cs
Labels: bug

#228 Free space management
  src/Paprika.Importer/Program.cs
  src/Paprika.Tests/Store/AbandonedTests.cs
  src/Paprika.Tests/Store/BasePageTests.cs
  src/Paprika.Tests/Store/DbTests.cs
  src/Paprika/Store/AbandonedList.cs
  src/Paprika/Store/AbandonedPage.cs
  src/Paprika/Store/BatchContextBase.cs
  src/Paprika/Store/DataPage.cs
  src/Paprika/Store/FanOutPage.cs
  src/Paprika/Store/IBatchContext.cs
  src/Paprika/Store/PagedDb.cs
  src/Paprika/Store/RootPage.cs
  src/Paprika/Utils/Printer.cs
Labels: bug, 🐌 performance

#234 Different path encoding
  src/Paprika.Tests/Store/RootPageTests.cs
  src/Paprika/Chain/PooledSpanDictionary.cs
  src/Paprika/Crypto/SpanExtensions.cs
  src/Paprika/Data/DataType.cs
  src/Paprika/Data/Key.cs
  src/Paprika/Store/RootPage.cs
Labels: 💾 disk size

#237 Precommit has a separate budget
  src/Paprika.Runner.Pareto/Program.cs
  src/Paprika.Runner/Program.cs
  src/Paprika.Tests/Chain/BlockchainTests.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Chain/IPersistenceStatsProvider.cs
Labels: 🌴Merkle

#238 Pooled dictionary fix
  src/Paprika.Tests/Chain/PooledSpanDictionaryTests.cs
  src/Paprika/Chain/PooledSpanDictionary.cs
Labels: bug

#241 Commit options and stats
  src/Paprika.Tests/Chain/BlockchainTests.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Chain/IPersistenceStatsProvider.cs
  src/Paprika/Chain/IStateStats.cs
  src/Paprika/Chain/IWorldState.cs
Labels: 🐌 performance

#240 Inline fanout
  src/Paprika.Tests/Store/PagedDbTests.cs
  src/Paprika/Store/AbandonedList.cs
  src/Paprika/Store/FanOutList.cs
  src/Paprika/Store/FanOutPage.cs
  src/Paprika/Store/Page.cs
  src/Paprika/Store/PageType.cs
  src/Paprika/Store/PagedDb.cs
  src/Paprika/Store/RootPage.cs
Labels: 🐌 performance

#242 Make Rlp.LengthOfLength branchless
  src/Paprika/RLP/Rlp.cs
Labels: 🐌 performance

#243 PooledSpanDictionary boost
  src/Paprika.Benchmarks/Paprika.Benchmarks.csproj
  src/Paprika.Benchmarks/PooledSpanDictionaryBenchmarks.cs
  src/Paprika.Tests/Categories.cs
  src/Paprika.Tests/Chain/BlockchainTests.cs
  src/Paprika.Tests/Chain/PooledSpanDictionaryTests.cs
  src/Paprika.Tests/Paprika.Tests.csproj
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Chain/PooledSpanDictionary.cs
Labels: 🐌 performance

#246 Faster SELF-DESTRUCTs
  src/Paprika.Tests/Chain/BlockchainTests.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Chain/PooledSpanDictionary.cs
  src/Paprika/Utils/Xor8.cs
Labels: 🐌 performance

#248 Volatile caching for read data
  src/Paprika.Tests/Chain/PooledSpanDictionaryTests.cs
  src/Paprika.Tests/Performance.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Chain/CacheBudget.cs
  src/Paprika/Chain/EntryType.cs
  src/Paprika/Chain/IPreCommitBehavior.cs
  src/Paprika/Chain/PooledSpanDictionary.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
  src/Paprika/Merkle/EntryType.cs
Labels: 🐌 performance

#249 Slotted array is path based again
  src/Paprika.Benchmarks/SlottedArrayBenchmarks.cs
  src/Paprika.Tests/Data/SlottedArrayTests.cs
  src/Paprika.Tests/Merkle/RootHashFuzzyTests.cs
  src/Paprika.Tests/Store/AbandonedTests.cs
  src/Paprika.Tests/Store/RootPageTests.cs
  src/Paprika.Tests/Utils/MetricsTests.cs
  src/Paprika/Data/NibblePath.cs
  src/Paprika/Data/SlottedArray.cs
  src/Paprika/Store/DataPage.cs
  src/Paprika/Store/FanOutPage.cs
  src/Paprika/Store/IPageVisitor.cs
  src/Paprika/Store/Page.cs
  src/Paprika/Store/RootPage.cs
  src/Paprika/Utils/Printer.cs
Labels: 💾 disk size, 💥Breaking

#252 StorageFanOutPage introduces
  src/Paprika.Tests/Store/PagedDbTests.cs
  src/Paprika/Store/FanOutList.cs
  src/Paprika/Store/Page.cs
  src/Paprika/Store/RootPage.cs
  src/Paprika/Store/StorageFanOutPage.cs
Labels: 🐌 performance, 💥Breaking

#253 New account hint introduced
  src/Paprika.Tests/Merkle/AdditionalTests.cs
  src/Paprika.Tests/TestExtensions.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Chain/IPreCommitBehavior.cs
  src/Paprika/Chain/IWorldState.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
Labels: 🐌 performance

#257 PooledSpanDictionary respects the lifecycle of UseOnce
  src/Paprika.Tests/Chain/PooledSpanDictionaryTests.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Chain/CacheBudget.cs
  src/Paprika/Chain/EntryType.cs
  src/Paprika/Chain/PooledSpanDictionary.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
Labels: bug

#258 Getting data for Merkle of Storage time reduced
  src/Paprika/Chain/Blockchain.cs
Labels: 🐌 performance

#259 Use pooled array for fp in Xor filter
  src/Paprika/Utils/Xor8.cs
Labels: 🐌 performance

#263 Revert "Simple leaf page"
  src/Paprika.Tests/Chain/BlockchainTests.cs
  src/Paprika.Tests/Data/SlottedArrayTests.cs
  src/Paprika.Tests/Merkle/AdditionalTests.cs
  src/Paprika.Tests/Store/BasePageTests.cs
  src/Paprika.Tests/Store/DataPageTests.cs
  src/Paprika.Tests/Store/DbTests.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Data/SlottedArray.cs
  src/Paprika/Merkle/CommitExtensions.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
  src/Paprika/Store/BatchContextBase.cs
  src/Paprika/Store/DataPage.cs
  src/Paprika/Store/IBatchContext.cs
  src/Paprika/Store/LeafPage.cs
  src/Paprika/Store/PageManagers/PointerPageManager.cs
  src/Paprika/Store/PagedDb.cs
  src/Paprika/Store/RootPage.cs
  src/Paprika/Utils/ReadOnlySpanOwner.cs
Labels: bug
