Repository NethermindEth/Paprika, pull requests merged in 2024-04, with the labels that each got.

#296 Batching file writes
  src/Paprika.Runner/Program.cs
  src/Paprika.Tests/Utils/SpanExtensionsTests.cs
  src/Paprika/Store/PageManagers/MemoryMappedPageManager.cs
  src/Paprika/Utils/SpanExtensions.cs
Labels: operating system, 🐌 performance

#299 Faster dictionary
  src/Paprika.Benchmarks/PooledSpanDictionaryBenchmarks.cs
  src/Paprika/Chain/PooledSpanDictionary.cs
Labels: 🐌 performance

#300 Account serialization
  src/Paprika.Benchmarks/AccountBenchmarks.cs
  src/Paprika/Account.cs
  src/Paprika/Crypto/Keccak.cs
  src/Paprika/Data/Serializer.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
Labels: 🐌 performance

#302 Optimize KeccakOrRlp
  src/Paprika.Benchmarks/KeccakOrRlpBenchmarks.cs
  src/Paprika/RLP/KeccakOrRlp.cs
Labels: 🐌 performance

#304 Optimize Serializer.ReadFrom
  src/Paprika.Benchmarks/SerializerBenchmarks.cs
  src/Paprika/Data/Serializer.cs
Labels: 🐌 performance

#307 Robustify RefCountingDisposable
  src/Paprika/Utils/RefCountingDisposable.cs
Labels: bug

#308 Aggressive flush to existing children
  src/Paprika/Store/DataPage.cs
Labels: 💾 disk size

#303 Optimize Rlp.LengthOf(UInt256 item)
  src/Paprika.Benchmarks/KeccakOrRlpBenchmarks.cs
  src/Paprika.Tests/Chain/BlockchainTests.cs
  src/Paprika.Tests/Merkle/HashingTests.cs
  src/Paprika/Crypto/Keccak.cs
  src/Paprika/Crypto/KeccakHash.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
  src/Paprika/Merkle/Hashing.cs
  src/Paprika/RLP/KeccakOrRlp.cs
  src/Paprika/RLP/Rlp.cs
  src/Paprika/RLP/RlpStream.cs
Labels: 🐌 performance

#309 Merkle Prefetcher
  .github/workflows/tests.yml
  src/Paprika.Tests/Chain/PrefetchingTests.cs
  src/Paprika.Tests/Merkle/RootHashFuzzyTests.cs
  src/Paprika.Tests/ReadForbiddingDb.cs
  src/Paprika.Tests/ReportTime.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Chain/IPreCommitBehavior.cs
  src/Paprika/Chain/IPreCommitPrefetcher.cs
  src/Paprika/Chain/IWorldState.cs
  src/Paprika/Chain/PooledSpanDictionary.cs
  src/Paprika/Data/Key.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
Labels: 🐌 performance, 🌴Merkle

#311 Faster UnPrepareKey
  src/Paprika.Benchmarks/SlottedArrayBenchmarks.cs
  src/Paprika/Data/NibblePath.cs
  src/Paprika/Data/SlottedArray.cs
Labels: 🐌 performance

#314 Minor test fixes
  src/Paprika.Tests/TestExtensions.cs
Labels: bug

#316 CPU prefetch
  src/Paprika.Tests/Store/BasePageTests.cs
  src/Paprika/Store/BatchContextBase.cs
  src/Paprika/Store/DataPage.cs
  src/Paprika/Store/IBatchContext.cs
  src/Paprika/Store/PageManagers/MemoryMappedPageManager.cs
  src/Paprika/Store/PageManagers/NativeMemoryPageManager.cs
  src/Paprika/Store/PageManagers/PointerPageManager.cs
  src/Paprika/Store/PagedDb.cs
Labels: 🐌 performance

#317 Use maxDegreeOfParallelism in Parallel.
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
Labels: bug

#319 Page management tests
  src/Paprika.Tests/Store/AbandonedTests.cs
  src/Paprika/Store/AbandonedList.cs
  src/Paprika/Store/AbandonedPage.cs
  src/Paprika/Store/BatchContextBase.cs
  src/Paprika/Store/IBatchContext.cs
  src/Paprika/Store/Page.cs
  src/Paprika/Store/PageManagers/MemoryMappedPageManager.cs
  src/Paprika/Store/PageManagers/NativeMemoryPageManager.cs
  src/Paprika/Store/PageManagers/PointerPageManager.cs
  src/Paprika/Store/PagedDb.cs
Labels: bug
