Repository NethermindEth/Paprika, pull requests merged in 2024-10, with the labels that each got.

#397 Different fanout
  src/Paprika.Tests/Store/AbandonedTests.cs
  src/Paprika.Tests/Store/PagedDbTests.cs
  src/Paprika/Store/DataPage.cs
  src/Paprika/Store/DbAddressList.cs
  src/Paprika/Store/IPageVisitor.cs
  src/Paprika/Store/Page.cs
  src/Paprika/Store/PageType.cs
  src/Paprika/Store/RootPage.cs
  src/Paprika/Store/StorageFanOut.cs
Labels: 💾 disk size, 💥Breaking

#408 New page fix
  src/Paprika/Store/PagedDb.cs
Labels: bug

#407 Use clearable pages
  src/Paprika.Tests/Store/ClearableTests.cs
  src/Paprika/Data/SlottedArray.cs
  src/Paprika/Store/AbandonedPage.cs
  src/Paprika/Store/DataPage.cs
  src/Paprika/Store/DbAddressList.cs
  src/Paprika/Store/IBatchContext.cs
  src/Paprika/Store/LeafOverflowPage.cs
  src/Paprika/Store/Page.cs
  src/Paprika/Store/StateRootPage.cs
  src/Paprika/Store/StorageFanOut.cs
Labels: 🐌 performance

#405 Bottom page
  src/Paprika.Runner/StatisticsForPagedDb.cs
  src/Paprika.Tests/Data/NibbleSelectorTests.cs
  src/Paprika.Tests/Data/SlottedArrayTests.cs
  src/Paprika.Tests/Store/AbandonedTests.cs
  src/Paprika.Tests/Store/BasePageTests.cs
  src/Paprika.Tests/Store/BottomPageTests.cs
  src/Paprika.Tests/Store/ClearableTests.cs
  src/Paprika.Tests/Store/DataPageTests.cs
  src/Paprika.Tests/Store/DbTests.cs
  src/Paprika.Tests/Store/PagedDbTests.cs
  src/Paprika.Tests/Store/TreeView.cs
  src/Paprika.Tests/Store/ValueReportingVisitor.cs
  src/Paprika.Tests/Store/ValueSquashingDictionaryVisitor.cs
  src/Paprika/Data/NibbleSelector.cs
  src/Paprika/Data/SlottedArray.cs
  src/Paprika/Store/BottomPage.cs
  src/Paprika/Store/DataPage.cs
  src/Paprika/Store/DbAddressList.cs
  src/Paprika/Store/IBatchContext.cs
  src/Paprika/Store/LeafOverflowPage.cs
  src/Paprika/Store/PageType.cs
  src/Paprika/Store/StatisticsVisitor.cs
  src/Paprika/Store/StorageFanOut.cs
Labels: 💾 disk size, 💥Breaking

#413 Minor public API changes
  src/Paprika.Tests/Store/PagedDbTests.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/IBatch.cs
  src/Paprika/IDb.cs
  src/Paprika/Store/BatchContextBase.cs
  src/Paprika/Store/IBatchContext.cs
  src/Paprika/Store/IPageManager.cs
  src/Paprika/Store/PageManagers/MemoryMappedPageManager.cs
  src/Paprika/Store/PageManagers/NativeMemoryPageManager.cs
  src/Paprika/Store/PageManagers/PointerPageManager.cs
  src/Paprika/Store/PagedDb.cs
Labels: docs

#412 Optimize AbandonedList Space Usage
  src/Paprika.Tests/Store/AbandonedTests.cs
  src/Paprika/Store/AbandonedList.cs
Labels: 💾 disk size, 💥Breaking

#416 Flush on empty queue
  src/Paprika/Chain/Blockchain.cs
Labels: 🐌 performance

#418 RawState much faster application
  src/Paprika/Chain/Blockchain.cs
Labels: 🐌 performance

#420 Span ownerhship improved
  src/Paprika.Tests/Merkle/RootHashFuzzyTests.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Chain/IPreCommitBehavior.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
  src/Paprika/Utils/ReadOnlySpanOwner.cs
Labels: bug, 🐌 performance, 🌴Merkle

#426 Prefetchers allocates less
  src/Paprika/Chain/Blockchain.cs
Labels: 🐌 performance

#427 Faster file io
  src/Paprika/Store/PageManagers/MemoryMappedPageManager.cs
Labels: operating system, 🐌 performance
