Repository NethermindEth/Paprika, pull requests merged in 2024-11, with the labels that each got.

#431 Different Merkle prefetching
  src/Paprika.Tests/Chain/PrefetchingTests.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Chain/IPreCommitBehavior.cs
  src/Paprika/Chain/IPreCommitPrefetcher.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
  src/Paprika/Merkle/Node.cs
Labels: bug, 🐌 performance

#433 BitFilter made faster
  src/Paprika.Benchmarks/Allocator.cs
  src/Paprika.Benchmarks/BitMapFilterBenchmarks.cs
  src/Paprika.Benchmarks/PageExtensionsBenchmarks.cs
  src/Paprika.Benchmarks/Paprika.Benchmarks.csproj
  src/Paprika.Benchmarks/SlottedArrayBenchmarks.cs
  src/Paprika.Tests/Data/BitMapFilterTests.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Data/BitMapFilter.cs
  src/Paprika/Data/PageExtensions.cs
Labels: 🐌 performance

#435 Better Merkle prefetcher
  src/Paprika.Tests/Chain/PrefetchingTests.cs
  src/Paprika/Chain/Blockchain.cs
  src/Paprika/Chain/IPreCommitPrefetcher.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
  src/Paprika/Merkle/RlpMemo.cs
Labels: bug, 🐌 performance

#438 Merkle Decompress fix
  src/Paprika.Tests/Chain/PrefetchingTests.cs
Labels: bug

#436 Unbalanced Parallel
  src/Paprika/Data/BitMapFilter.cs
  src/Paprika/Merkle/ComputeMerkleBehavior.cs
  src/Paprika/Utils/ParallelUnbalancedWork.cs
Labels: 🐌 performance

#440 BitFilter clearing made parallel
  src/Paprika/Data/BitMapFilter.cs
Labels: 🐌 performance
